/**
 * Access data hooks: `profiles` (app users) and `roles` (RBAC). Mock-phase
 * stand-in for what becomes `auth.users` + a `profiles`/`roles` pair in the
 * Supabase schema — there's no real invite flow yet, just local rows a
 * settings screen can create/edit.
 */
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { crud } from "@/data/store";
import type { Profile, Role } from "@/domain/types";
import { MUTATION_DEFAULTS, QUERY_DEFAULTS, queryKeys } from "@/data/hooks/keys";

// ---- Profiles --------------------------------------------------------------

export function useProfiles() {
  return useQuery({
    queryKey: queryKeys.profiles,
    queryFn: () => crud("profiles").list(),
    ...QUERY_DEFAULTS,
  });
}

/**
 * `profiles.userId` mirrors Supabase's `auth.users.id` in the real (F2)
 * schema, so it's caller-supplied rather than autogenerated by the store
 * (see `store.ts`'s `AUTO_ID` — false for `profiles`) — a real signup would
 * supply it from `auth.users`. Here, the mock "invite" mints it directly:
 * the new profile is active immediately (no pending-invite state to model
 * yet), since the real email invite only arrives in the database phase.
 */
export function useCreateProfile() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (input: { name: string; roleId: string }) =>
      crud("profiles").create({
        userId: crypto.randomUUID(),
        name: input.name,
        roleId: input.roleId,
        active: true,
      }),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: queryKeys.profiles }),
    ...MUTATION_DEFAULTS,
  });
}

/** `profiles`' primary key is `userId`, not `id` — `crud("profiles")` is keyed on it (see `store.ts`'s `ID_FIELD`). */
export function useUpdateProfile() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({ userId, patch }: { userId: string; patch: Partial<Profile> }) =>
      crud("profiles").update(userId, patch),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: queryKeys.profiles }),
    ...MUTATION_DEFAULTS,
  });
}

// ---- Roles ------------------------------------------------------------------

export function useRoles() {
  return useQuery({
    queryKey: queryKeys.roles,
    queryFn: () => crud("roles").list(),
    ...QUERY_DEFAULTS,
  });
}

export function useCreateRole() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async (input: Omit<Role, "id">) => crud("roles").create(input),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: queryKeys.roles }),
    ...MUTATION_DEFAULTS,
  });
}

export function useUpdateRole() {
  const queryClient = useQueryClient();
  return useMutation({
    mutationFn: async ({ id, patch }: { id: string; patch: Partial<Role> }) => crud("roles").update(id, patch),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: queryKeys.roles }),
    ...MUTATION_DEFAULTS,
  });
}
