/**
 * The mock data store — this IS the app's backend until the Supabase phase.
 * Every screen reads it through hooks in `src/data/hooks/` (never directly).
 * Persisted to `localStorage` as one JSON blob, cached in-memory as a
 * singleton after the first `loadDB()` so repeated calls are free and
 * always see the same object.
 */
import { buildSeed, type MockDB } from "@/data/seed";
import { todayISO } from "@/lib/format";
import type { Evento } from "@/domain/types";

export type { MockDB };

const DB_KEY = "allegra-db-v1";

let cachedDB: MockDB | null = null;

function isMockDB(value: unknown): value is MockDB {
  if (typeof value !== "object" || value === null) return false;
  const keys: (keyof MockDB)[] = [
    "profiles",
    "roles",
    "eventTypes",
    "services",
    "serviceVariants",
    "transactionCategories",
    "pipelineStages",
    "events",
    "eventServices",
    "transactions",
    "teamMembers",
    "contacts",
    "proposals",
    "proposalServices",
    "activities",
  ];
  return keys.every((key) => Array.isArray((value as Record<string, unknown>)[key]));
}

/**
 * Loads the mock database: from the in-memory cache if already loaded,
 * otherwise from `localStorage`. When storage is absent or holds anything
 * other than a well-formed `MockDB` (corrupt JSON, wrong shape), builds a
 * fresh seed relative to today, persists it, and caches it.
 */
export function loadDB(): MockDB {
  if (cachedDB) return cachedDB;

  const raw = localStorage.getItem(DB_KEY);
  if (raw !== null) {
    try {
      const parsed: unknown = JSON.parse(raw);
      if (isMockDB(parsed)) {
        cachedDB = parsed;
        return cachedDB;
      }
    } catch {
      // corrupt JSON — fall through to reseed below
    }
  }

  cachedDB = buildSeed(todayISO());
  saveDB(cachedDB);
  return cachedDB;
}

/** Persists `db` to `localStorage` and makes it the in-memory singleton. */
export function saveDB(db: MockDB): void {
  cachedDB = db;
  localStorage.setItem(DB_KEY, JSON.stringify(db));
}

/** Discards stored data, builds a fresh seed relative to today, and persists it. */
export function resetDB(): MockDB {
  const fresh = buildSeed(todayISO());
  saveDB(fresh);
  return fresh;
}

// ---- Generic CRUD -------------------------------------------------------

/**
 * Every entity's primary key is `id`, except `profiles` — its `userId`
 * mirrors Supabase's `auth.users.id` in the real (F2) schema, so it isn't
 * autogenerated by the mock store either (a real signup would supply it).
 */
const ID_FIELD: Record<keyof MockDB, string> = {
  profiles: "userId",
  roles: "id",
  eventTypes: "id",
  services: "id",
  serviceVariants: "id",
  transactionCategories: "id",
  pipelineStages: "id",
  events: "id",
  eventServices: "id",
  transactions: "id",
  teamMembers: "id",
  contacts: "id",
  proposals: "id",
  proposalServices: "id",
  activities: "id",
};

/** Whether `create()` should autogenerate this resource's primary key. */
const AUTO_ID: Record<keyof MockDB, boolean> = {
  profiles: false,
  roles: true,
  eventTypes: true,
  services: true,
  serviceVariants: true,
  transactionCategories: true,
  pipelineStages: true,
  events: true,
  eventServices: true,
  transactions: true,
  teamMembers: true,
  contacts: true,
  proposals: true,
  proposalServices: true,
  activities: true,
};

/** Whether this resource has a `createdAt` field for `create()` to autofill. */
const AUTO_CREATED_AT: Record<keyof MockDB, boolean> = {
  profiles: false,
  roles: false,
  eventTypes: false,
  services: false,
  serviceVariants: false,
  transactionCategories: false,
  pipelineStages: false,
  events: true,
  eventServices: true,
  transactions: true,
  teamMembers: false,
  contacts: true,
  proposals: true,
  proposalServices: false,
  activities: true,
};

function idOf<K extends keyof MockDB>(key: K, item: MockDB[K][number]): string {
  const record = item as unknown as Record<string, string>;
  return record[ID_FIELD[key]];
}

export interface Crud<T> {
  list(): T[];
  get(id: string): T | null;
  create(input: Omit<T, "id" | "createdAt">): T;
  update(id: string, patch: Partial<T>): T;
  remove(id: string): void;
}

/**
 * A type-safe CRUD surface over one resource of the mock database. Every
 * mutation persists immediately (loads the current db, mutates it, saves
 * it once). `update`/`remove` throw when `id` doesn't resolve to a row.
 */
export function crud<K extends keyof MockDB>(key: K): Crud<MockDB[K][number]> {
  type T = MockDB[K][number];

  function findIndex(id: string): number {
    return (loadDB()[key] as T[]).findIndex((item) => idOf(key, item) === id);
  }

  return {
    list() {
      return [...(loadDB()[key] as T[])];
    },

    get(id) {
      return (loadDB()[key] as T[]).find((item) => idOf(key, item) === id) ?? null;
    },

    create(input) {
      const record = { ...input } as Record<string, unknown>;
      if (AUTO_ID[key]) record[ID_FIELD[key]] = crypto.randomUUID();
      if (AUTO_CREATED_AT[key]) record.createdAt = new Date().toISOString();
      const entity = record as unknown as T;

      const db = loadDB();
      (db[key] as T[]).push(entity);
      saveDB(db);
      return entity;
    },

    update(id, patch) {
      const db = loadDB();
      const list = db[key] as T[];
      const index = findIndex(id);
      if (index === -1) {
        throw new Error(`Não foi possível atualizar: registro não encontrado (id "${id}").`);
      }
      const updated = { ...list[index], ...patch };
      list[index] = updated;
      saveDB(db);
      return updated;
    },

    remove(id) {
      const db = loadDB();
      const list = db[key] as T[];
      const index = findIndex(id);
      if (index === -1) {
        throw new Error(`Não foi possível remover: registro não encontrado (id "${id}").`);
      }
      list.splice(index, 1);
      saveDB(db);
    },
  };
}

// ---- convertLead ---------------------------------------------------------

/**
 * Converts an accepted proposal into an event: the one multi-table
 * operation in the store (mirrors the future `convert_lead` Supabase RPC).
 * Validates, mutates the whole db in memory, then persists once — so a
 * rejection never leaves a half-converted lead behind.
 */
export function convertLead(input: {
  contactId: string;
  proposalId: string;
  eventName: string;
  eventTypeId: string;
  eventDate: string;
  eventTime: string | null;
}): Evento {
  const db = loadDB();

  const proposal = db.proposals.find((p) => p.id === input.proposalId);
  if (!proposal || proposal.contactId !== input.contactId) {
    throw new Error("Proposta não encontrada para este contato.");
  }
  if (proposal.status !== "accepted") {
    throw new Error("A proposta precisa estar aceita para converter o lead em evento.");
  }
  if (db.events.some((ev) => ev.contactId === input.contactId)) {
    throw new Error("Este contato já foi convertido em evento.");
  }

  const now = new Date().toISOString();
  const event: Evento = {
    id: crypto.randomUUID(),
    name: input.eventName,
    eventTypeId: input.eventTypeId,
    eventDate: input.eventDate,
    eventTime: input.eventTime,
    contactId: input.contactId,
    discountCents: proposal.discountCents,
    canceled: false,
    notes: null,
    createdAt: now,
  };
  db.events.push(event);

  for (const item of db.proposalServices.filter((p) => p.proposalId === proposal.id)) {
    db.eventServices.push({
      id: crypto.randomUUID(),
      eventId: event.id,
      serviceId: item.serviceId,
      variantId: item.variantId,
      priceCents: item.priceCents,
      createdAt: now,
    });
  }

  saveDB(db);
  return event;
}

// ---- canInactivateStage ---------------------------------------------------

/** False iff some non-archived contact still sits on this pipeline stage. */
export function canInactivateStage(stageId: string): boolean {
  const db = loadDB();
  return !db.contacts.some((contact) => contact.stageId === stageId && !contact.archived);
}
